// Code generated by /var/folders/93/11pwhrmj2q10y6_zzp5_g0lr0000gp/T/go-build2752069505/b001/exe/deep-copy --root .; DO NOT EDIT.

package testdata

// DeepCopy generates a deep copy of *YourStruct
func (o *YourStruct) DeepCopy() *YourStruct {

	if o == nil {
		return nil
	}
	var cp YourStruct
	var val = *o
	cp.Field1 = val.Field1
	cp.Field2 = val.Field2
	cp.field3 = val.field3
	return &cp
}

// clone generates a deep copy of AnotherStruct
func (o AnotherStruct) clone() AnotherStruct {

	var cp AnotherStruct
	if o.S != nil {
		cp.S = o.S.DeepCopy()
	}
	return cp
}
