// Code generated by /var/folders/93/11pwhrmj2q10y6_zzp5_g0lr0000gp/T/go-build1945655396/b001/exe/deep-copy --root .; DO NOT EDIT.

package testdata

// DeepCopy generates a deep copy of *C
func (o *C) DeepCopy() *C {

	if o == nil {
		return nil
	}
	var cp C
	var val = *o
	if val.M != nil {
		cp.M = make(map[string]string, len(val.M))
		for k2, v2 := range val.M {
			var cp_k2 string
			cp_k2 = k2
			var cp_v2 string
			cp_v2 = v2
			cp.M[cp_k2] = cp_v2
		}
	}
	return &cp
}

// DeepCopy generates a deep copy of *S
func (o *S) DeepCopy() *S {

	if o == nil {
		return nil
	}
	var cp S
	var val = *o
	cp.Age = val.Age
	cp.Name = val.Name
	if val.Sex != nil {
		*cp.Sex = *val.Sex
	}
	if val.S != nil {
		var sink_2 []*C
		var source_2 = *val.S
		sink_2 = make([]*C, len(source_2))
		for i3 := range source_2 {
			if source_2[i3] != nil {
				sink_2[i3] = source_2[i3].DeepCopy()
			}
		}
		cp.S = &sink_2
	}
	return &cp
}

// DeepCopy generates a deep copy of *List
func (o *List) DeepCopy() *List {

	if o == nil {
		return nil
	}
	var cp List
	var val = *o
	cp = make([]S, len(val))
	for i := range val {
		{
			cp[i] = *val[i].DeepCopy()
		}
	}
	return &cp
}
